YELLOW_TAXI_TRIPS = "yellow_taxi_trips"
DIM_TRIP_DATETIME = "dim_trip_datetime"
DIM_TRANSACTION_FEES = "dim_transaction_fees"
DIM_TRIP_LOCATION = "dim_trip_location"
DIM_TRIP_MISC_DETAILS = "dim_trip_misc_details"
TAXI_ZONE_LOOKUP = "taxi_zone_lookup"
