TABLE_YELLOW_TAXI_TRIPS = "yellow_taxi_trips"
TABLE_DIM_TRIP_DATETIME = "dim_trip_datetime"
TABLE_DIM_TRANSACTION_FEES = "dim_transaction_fees"
TABLE_DIM_TRIP_LOCATION = "dim_trip_location"
TABLE_TAXI_ZONE_LOOKUP = "taxi_zone_lookup"
